buildwithgrove/path

.gitignore, config/config.go, config/config.schema.yaml, config/config_test.go, request/errors.go, request/parser.go, request/qos_provider.go
This PR fixes a bug where the `gateway` package would panic due to `parser.GetHTTPErrorResponse` returning a nil value when a service request is sent for a service not configured in the config YAML.
=> fix: resolves panic when endpoint called for an unassigned service

.github/workflows/main-build.yml, .github/workflows/release-artifacts.yml
Fix for build workflow.
This fix solves the issue with build workflow being triggered by pull requests. Instead, it changes the behavior to be triggered only by main branch.
#17
=> Fix build workflow to trigger only for main branch

.github/workflows/main-build.yml
Two main changes:
- Always tag the latest image with `latest`
- Use a shortened version of the `sha`
Where images are stored: https://github.com/buildwithgrove/path/pkgs/container/path
=> [Docker] Update the tag of the built and published docker images

README.md
Adding deployment visibility in the Path repository for Path deployment
- Added status badge for ArgoCD Path deployment status.
- Fix config connector resources preventing Path deployment to function correctly.
=> Added status badge for ArgoCD path deployment

cmd/.config.shannon_example.yaml, config/config.schema.yaml, config/config_test.go, config/testdata/shannon.example.yaml, e2e/scripts/update_shannon_config_from_secrets.sh, e2e/shannon.example.yaml, protocol/shannon/config.go
* Update `Shannon` config example `cmd/.config.shannon_example.yaml` to comply with the new parser.
* Fix `Gateway` and `Application` config entry names `*_hex_private_key` -> `*_private_key_hex`
* Fix test config indentation.
=> [Config] Revamp Shannon config example

.github/workflows/release-artifacts.yml
Change the worklow trigger from `workflow_run` which was pointing to the wrong branch to trigger to `push` which will trigger release creation when pushing to `main` branch.
=> [READY] Change trigger workflow from workflow_run to push

Makefile
This PR changes to the `Makefile` to update `copy_shannon_config` and `copy_morse_config` destination directory to `./config`.
=> Update Makefile config copy location

local/kubernetes/path-values.yaml, makefiles/localnet.mk
Fix typo in makefile and update mountSecrets block to the proper path, causing Path container to break both locally and in staging env.
=> [PATCH] [READY] Fix `values.yaml` and small typo in makefile

config/service_alias.go
adding all morse EVMs to `service_alias.go`. This will help enable users to launch on MORSE ASAP specifically with the F-chains cutover. 
This is a requirement on behalf of Chainstack (and any live Morse gateway) to cutover from Gateway Server -> Path in the immediate. This also aligns nicely from a timing standpoint given that the set of chains will be perfectly defined by the Foundation on 12/18 in accordance with this list of chains: https://docs.google.com/spreadsheets/d/1QWVGEuB2u5bkGfONoDNaltjny1jd9rJ_f7HZTjSGgQM/
=> [Morse Support] All Morse EVM IDs to `service_alias` map

Makefile, cmd/qos.go, config/service_alias.go, e2e/docker_test.go, e2e/morse_relay_test.go
- Add back `0021` used in E2E tests
- Separate Morse, Shannon and test service IDs
- Logically group different service IDs w/in Morse
=> [Test Fixes] Followup to #103 add Morse/Shannon/Service IDs

Makefile, docusaurus/docs/develop/path/introduction.md
Add details on how to get the configuration file for Morse E2E tests.
A valid config file is needed to run Morse E2E tests, with several fields' values not readily available due to being sensitive data items.
=> [Docs] Add config location for Morse E2E tests

Dockerfile
Optimize the E2E tests time by reducing the image build time through moving the COPY instruction to the bottom of the image building instructions.
Reduce E2E tests runtime.
=> Fix: move COPY source to the bottom of the Dockerfile build instructions

README.md, docusaurus/docs/operate/operate.md, docusaurus/docusaurus.config.js
This PR adds just a brief tidbit to the README.md file which instructs PATH users, when needing technical support to reach out via Discord. In addition, it adds instructions to open bug reports and/or enhancement requests to the GitHub Issues.
=> Adding link to Discord to README.md and instructions for Technical Support

qos/jsonrpc/response.go
https://github.com/buildwithgrove/path/pull/130 contained a small bug re: the `jsonrpc.Response` struct's `ID` and `Version` fields, which were missing the type definitions. This PR fixes that bug.
=> fix: bug fix from json rpc response struct field types

.github/workflows/main-build.yml, .github/workflows/upload-pages-artifact.yml
Upgrade github ations from `v3` to `v4`.
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
https://github.com/buildwithgrove/path/actions/runs/12935368023/job/36078630477
=> [Workflows] Update GitHub actions from v3 to v4

docusaurus/docs/develop/path/path_config.md
This PR aims to fix a small typo in the Path Config documentation.
- Description: Fix typo in PATH config
=> [docs] fix typo in PATH config

docusaurus/docs/README.md
> [!IMPORTANT]  
> Note to reviewer
> @Olshansk  is still iterating on the naming. Looking for feedback ons structure, naming and visuals for now. **This is an iteration, not the final product.**
Adding the following section (per feedback from Alchemy) to make it a bit easier to start understanding who/why should use `PATH`.
=> [Docs] Adding diagrams to main page of path.grove.city

config/service_qos.go
Adding February new chains to path.
Changes:
Adds the following chains:
- XRPL EVM Sidechain | `F02C`
- Sonic | `F02D`
- Tron | `F02E`
- Linea | `F030`
- Berachain bArtio Testnet | `F031`
- Ink | `F032`
- Mantle | `F033`
- Sei | `F034`
- Berachain | `F035`
=> Adding february new chains to Path

Dockerfile, Makefile, Tiltfile, cmd/metrics.go, docusaurus/docs/develop/path/cheat_sheet_morse.md, docusaurus/docs/develop/path/cheat_sheet_shannon.md, docusaurus/docs/develop/path/env_setup.md, docusaurus/docs/develop/path/qos.md, docusaurus/docs/develop/path/troubleshooting_faq.md, docusaurus/docusaurus.config.js, docusaurus/src/css/custom.css, gateway/request_context.go, local/scripts/install_tools.sh, makefiles/configs.mk, makefiles/debug.mk, makefiles/test_requests.mk, metrics/gateway.go, metrics/qos/evm.go, proto/path/gateway.proto, proto/path/metadata/metadata.proto, proto/path/qos/evm.proto, qos/evm/response_blocknumber.go, qos/evm/response_chainid.go, qos/evm/response_generic.go
This PR contains manual changes made during the final review of #152 to expedite the E2E review process.
- Update the main `Dockerfile` to avoid redownloading all dependencies every time
- Remove `pprof` from cheatsheets and move it to `FAQ` because devs just want to get through to the end
- Add `graphviz` to list of required dependencies
- Misc NITs & documentation improvements
- Minor improvements to docs UX
I have verified that when I check out `main`, the `make test_request__endpoint_url_path_mode__no_auth__service_id_header` works.
With these changes, I get `no healthy upstream` 100% of the time.
```
make test_request__endpoint_url_path_mode__no_auth__service_id_header
##################################################################################################################### …
```
=> [WIP][Review] Review of #152: `First implementation of relay metrics observability`

cmd/main.go, cmd/morse.go, protocol/morse/protocol.go
Fix Morse logger to use global logger instead of initializing its own.
- Updated the `getMorseProtocol` function to pass the `logger` as the primary argument, ensuring a global logger is used consistently across function calls.
- Modified the `NewProtocol` function to remove the initialization of its own logger, replacing it with the provided global `logger` as an argument.
- Removed the unused `context` package import, cleaning up the import statements.
- Adjusted the parameter order in function signatures for consistency and clarity.
=> [FIX][LOGGER] Fix Morse logger to use global logger instead of initializing its own

qos/evm/evm.go, qos/jsonrpc/params.go, qos/jsonrpc/request.go, qos/jsonrpc/request_test.go
Support an array of objects as `params` field value in JSONRPC requests.
Changes:
- Add a new `Params` struct under `qos/jsonrpc` package
- Add unit tests to cover different formats of the `params` field in a JSONRPC request.
- Add a TODO for looking into batch JSONRPC requests.
- Description: Request parsing fails for raw payloads representing JSONRPC requests with `params` field value as an array of objects.
- For `path_up_standalone` with `anvil` on `Shannon`: `make test_request__relay_util_1000`
- For `path_up` with `anvil` on `Shannon`: `make test_request__envoy_relay_util_100`
- For `path_up` with `F00C` on `Morse`: `make test_request__relay_util_100_F00C_via_envoy`
=> [QoS] Support array of objects as JSONRPC params

qos/jsonrpc/params.go, qos/jsonrpc/request.go, qos/jsonrpc/request_test.go
Improve JSON-RPC parameter validation and request serialization handling
- Enhanced `Params` type validation to properly handle objects and arrays per JSON-RPC 2.0 spec
- Added custom `Request` marshaling to handle empty fields correctly 
- Added `IsEmpty()` method to control omission of optional fields in serialization
- Added comprehensive test cases with examples from Ethereum, Polkadot and Solana docs
- Improved code documentation with detailed parameter type examples
- Updated error messages to be more descriptive## Issue
- Description: `params` field of the JSONRPC requests can be omitted in the request. 
- For `path_up_standalone` with `anvil` on `Shannon`: `make test_request__relay_util_1000`
- For `path_up` with `anvil` on `Shannon`: `make …
=> feat(jsonrpc): Enhance request parameter validation and serialization

README.md
Remove ArgoCD status badge from README
Changes:
- `README.md`
N/A
- For `path_up_standalone` with `anvil` on `Shannon`: `make test_request__relay_util_1000`
- For `path_up` with `anvil` on `Shannon`: `make test_request__envoy_relay_util_100`
- For `path_up` with `F00C` on `Morse`: `make test_request__relay_util_100_F00C_via_envoy`
=> Remove ArgoCD broken status badge

docusaurus/docs/operate/helm/3_guard.md, docusaurus/docs/operate/helm/5_values.md
Update embedded Helm chart documentation links to point to the `main` branch of the Helm repository.
- Updated embedded Helm chart documentation links from `guard-docs` branch to `main` branch
- Removed outdated TODO comments referencing the transition from `guard-docs` branch
=> [docs] Fix embedded helm chart docs to point to main branch of helm repo

Makefile
< One line summary>
Changes:
- < Change 1 >
- < Change 2 >
- Description: < Description >
- Issue: #{ISSUE_NUMBER}
- For `Shannon` with `anvil`: `make test_request__envoy_relay_util_100`
=> Put back erroneously deleted make path_run target

.github/pull_request_template.md, Makefile, Tiltfile, makefiles/localnet.mk, makefiles/test.mk, makefiles/test_requests.mk, metrics/protocol/morse/metrics.go
Reduce Metrics cardinality by using Prometheus Exemplars for high cardinality values.
Changes:
- Use Prometheus Exemplars in PATH Morse metrics (low cardinality elsewhere)
- Fix the Port-forwading to Grafana issue in Local development environment.
- Description: High cardinality of PATH metrics
- Issue: #219 
- For `Shannon` with `anvil`: `make test_request__envoy_relay_util_100`
=> [Metrics] Fix metrics cardinality

.github/workflows/main-build.yml
So we don't have to trigger manually wait for the new image build..
=> [CI] build image on merge to main branch

qos/cometbft/cometbft.go, qos/cometbft/request.go, qos/error_context.go, qos/http.go, qos/jsonrpc/errors.go, qos/solana/request.go, qos/solana/solana.go
Implement error context for Solana and CometBFT QoS.
- Added a shared error context to `qos` package.
- Use the new error context in Solana and CometBFT.
Panic in Solana and CometBFT on internal errors/invalid requests.
=> [QoS] Fix solana observations panic

protocol/morse/errors.go
Fix the Morse integration error pattern rule on SDK errors.
Fix the Morse integration error pattern rule on SDK errors.
Endpoint errors not captured due to incorrect pattern used for sanctioning endpoints with errors.
=> Fix: update Morse pocketcore error pattern match rules

qos/evm/qos.go, qos/evm/request_validator.go
Set Service ID on EVM organic requests' observations.
- Set the service ID field on all organic requests' observations (successful or failed) on EVM QoS.
Warning log entries showing missing Service ID from EVM observations.
=> [QoS] Set ServiceID on EVM organic requests observations

metrics/protocol/morse/metrics.go
Fix bug/typo in Morse metrics success calculation.
- Fix the typo in success calculator function.
Incorrect Success label setting.
=> Fix success label processor in Morse metrics

qos/solana/qos.go, qos/solana/request_validator.go
Set the Endpoint Store on Solana Request Context.
- Set the Endpoint Store on Solana Request Context.
Endpoint selection will cause a panic without the endpoint store set.
=> [QoS][Solana] Fix: Set endpointStore on request context

cmd/data.go, config/config.schema.yaml, config/data_reporter.go, data/reporter_http.go, docusaurus/docs/develop/path/5_configurations_path.md
Add configurable HTTP POST timeout for data reporter
- Add PostTimeoutMS field to DataReporterHTTP struct
- Implement configurable timeout for HTTP POST operations with default of 10 seconds
- Create custom HTTP client with timeout instead of using standard http.Post
- Add YAML configuration option post_timeout_ms to HTTPDataReporterConfig
- Include proper cleanup with defer resp.Body.Close() in HTTP request handler
- Add documentation for timeout configuration parameters
Increase in number of goroutines if the Data Pipeline is turned off.
=> [Data] Add configurable HTTP POST timeout for data reporter

e2e/config/services_shannon.yaml
< ONE_LINE_SUMMARY>
- Changed service ID for Optimism from `optimism` -> `op`
- Changed service ID for Optimism Sepolia Testnet from `optimism_sep_test` -> `op_sep_test`
=> [OPTIMISM][E2E] Correcting service id for `optimism` -> `op`

gateway/request_context.go
Bug fix: missing return was causing incorrect log lines on protocol observation update.
- Added a missing return.
Missing return was causing incorrect log lines on protocol observation update.
=> Fix: update protocol observations returns after update

cmd/shannon.go, protocol/shannon/fullnode_cache.go, protocol/shannon/mode_centralized.go, protocol/shannon/protocol.go
Optimize owned apps storage and lookup by converting from slice to map structure to avoid excessive looping.
Implements TODO:
```go
// TODO_IMPROVE(@commoddity, @adshmh): This function currently loops through all apps owned by the gateway.
// Without a caching FullNode, this results in extremely slow behaviour. We should look into improving the
// efficiency of this lookup to get the list of apps owned by the gateway.
```
- Convert `OwnedApp` slice to `OwnedApps` map structure for efficient service-based lookups
- Remove redundant looping through all owned apps when checking service-specific apps
- Implement direct service ID to app addresses mapping in centralized gateway mode
=> [Shannon] Make OwnedApps a map to avoid excess looping calls to GetSession

e2e/config/services_shannon.yaml
Load tests can now be run against pocket-beta1, pocket-beta2, pocket-beta3, pocket-beta4, and pocket-beta5 services.
- Updated the services_shannon.yaml with new services on beta testnet.
Need to load test pocket services on beta testnet.
=> [Load Test] Add pocket-beta1-5 services to load tests

go.mod, go.sum, observation/protocol/shannon.pb.go, proto/path/protocol/shannon.proto, protocol/shannon/fullnode_cache.go, protocol/shannon/sanctions.go
Enhance Shannon endpoint error handling with new error types on relay response validation.
- Upgrade shannon-sdk from v0.0.0-20250603210336-969a825fddd5 to v0.0.0-20250615013032-bbc533b256f4
- Add 5 new ShannonEndpointErrorType enum values for payload unmarshal, response validation, public key errors, and signature validation
- Implement error classification logic in sanctions.go to map specific SDK errors to appropriate endpoint error types and sanction levels
- Enable GetApp method in cachingFullNode by delegating to lazyFullNode instead of returning a NoOp error
- Update generated protobuf files (shannon.pb.go) to reflect new enum values
Relay response validation errors were not used for sanctioning, keeping bad endpoints in the endpoint selection pool:
1. PATH queries FullNode1
2. …
=> [Protocol][Shannon] Shannon handles endpoint errors on relay response validation

cmd/data.go, cmd/main.go, cmd/morse.go, cmd/shannon.go, e2e/docker_test.go, e2e/service_evm_test.go, e2e/service_solana_test.go, protocol/morse/context.go, protocol/morse/errors.go, protocol/shannon/protocol.go, qos/cometbft/observe.go, qos/cometbft/store.go, qos/evm/endpoint_selection.go, qos/evm/endpoint_store.go, qos/evm/service_state.go, qos/jsonrpc/params.go, qos/solana/observe.go
> [!NOTE]
> Key changes are in `qos/evm/endpoint_selection.go`
In an attempt to answer this question:
I found this log line in [the dashboard](https://grafana.tooling.grove.city/goto/uTj5sSPHg?orgId=1) and improved it.
```bash
// map[app_kubernetes_io_instance:path-shannon-mainnet app_kubernetes_io_managed_by:Helm app_kubernetes_io_name:path-shannon-mainnet app_kubernetes_io_version:0.0.16 cluster:portal-prd-europe-west3 container:path-shannon-mainnet deploymentname:path-shannon-mainnet endpoint_addr:pokt14jk2s5lrgxjw9yd5kwzj0jxgr2727vxa72g6r6-https://fra.spacebelt.cloud error:endpoint has not returned an archival balance response to a "eth_getBalance" request evm_chain_id:0x89 filename:/var/log/pods/middleware_path-shannon-mainnet-b9fdd766c-qf8nf_6330216e-4549-4749-b296-43fafa65f375/path- …
```
=> Minor error improvements in logging

.github/workflows/main-build.yml, .serena/project.yml, Dockerfile.release, makefiles/release.mk
Add multi-architecture Dockerfile and cross-platform release build targets
- Added `Dockerfile.release` to support building multi-architecture Docker images using pre-built binaries
- Introduced `release_build_cross`, `release_clean`, and `release_build_local` Makefile targets for cross-platform binary builds
- Included architecture-specific binary copying logic in the Dockerfile using `TARGETARCH` argument
- Configured non-root container user setup and binary execution environment
* For `Shannon` with `anvil`: `make test_request__shannon_relay_util_100`
* For `Morse` with `F00C`: `make test_request__morse_relay_util_100`
=> build multiarch quickly

api/path_openapi.yaml, config/service_qos_config.go, docusaurus/docs/learn/qos/1_supported_services.md, e2e/config/.grove.archival.e2e_load_test.config.yaml, e2e/config/.grove.e2e_load_test.config.yaml, e2e/config/services.schema.yaml, e2e/config/services_shannon.yaml, e2e/scripts/shannon_preliminary_services_test.sh, makefiles/test.mk, qos/evm/state_archival.go
Bringing services back in line with the onchain service IDs that are now cleaned up.
- Update services in accordance with https://docs.google.com/spreadsheets/d/1QWVGEuB2u5bkGfONoDNaltjny1jd9rJ_f7HZTjSGgQM/edit?gid=195862478#gid=195862478 to the new naming conventions.
- Add `xrplevm` preliminarily to the codebase
- https://github.com/pokt-network/poktroll/issues/1526
=> [SERVICE] Revised service IDs for onchain cleanup

.gitignore, .serena/memories/code_style_conventions.md, .serena/memories/metrics_patterns.md, .serena/memories/project_overview.md, .serena/memories/suggested_commands.md, .serena/memories/task_completion_checklist.md, cmd/main.go, metrics/gateway.go
Add version metrics to PATH gateway for deployment tracking and monitoring
- Add Version, Commit, and BuildDate variables to main package for ldflags injection
- Add `path_version_info` gauge metric with version, commit, and build_date labels to Prometheus metrics
- Initialize version metric during application startup with `SetVersionInfo()` function
- Update .gitignore to include release directory and .serena/cache for MCP servers
- Import metrics package in main.go to access SetVersionInfo function
- Register versionInfo metric in Prometheus during metrics initialization
=> feat: add Prometheus metric to expose PATH version information

e2e/config_test.go, local/kind-config.yaml, observation/qos/evm.pb.go, proto/path/qos/evm.proto, qos/evm/endpoint.go, qos/evm/endpoint_selection.go, qos/evm/endpoint_store.go, qos/evm/response.go, qos/evm/response_generic.go, qos/evm/service_state.go, qos/solana/response_generic.go
Enhanced QoS endpoint validation with invalid response tracking and improved Kind cluster logging configuration
- Add invalid response tracking to endpoint validation with 30-minute timeout for endpoint disqualification
- Implement EVMUnrecognizedResponse observation handling to trigger sanctions on endpoints returning unparseable responses
- Update generic response handling to use already-parsed JSON-RPC responses and set proper validation errors
- Configure comprehensive log retention in Kind cluster with 1GB max size and 10 file rotation
- Add containerd garbage collection tuning to prevent aggressive log cleanup
- Update protobuf comments to clarify EVMUnrecognizedResponse usage for QoS endpoint selection
- 400 HTTP HTTP Status codes returned in response  to valid requests if endpoint …
=> [QoS][EVM] Fix: QoS handles malformed endpoint responses for all requests

qos/evm/check_blocknumber.go, qos/evm/endpoint_selection.go, qos/evm/service_state.go
Fix EVM QoS validation failures caused by incorrect perceived block number calculation and pointer dereferencing in error messages
- Fix perceived block number calculation to use maximum across endpoints instead of overwriting with last endpoint
- Fix pointer dereferencing in block number and chain ID error messages to show actual values instead of memory addresses
- Add explanatory comments for validation logic fixes with references to field documentation
- Improve error message clarity for debugging QoS validation issues
=> [QoS] Fix & improve perceived block number updates and validation

qos/evm/context.go, qos/evm/response.go
Include Endpoint Address in log indicating unmarshal failure
- Include Endpoint Address in log indicating unmarshal failure
Log lines did not indicate the address of the endpoint with payload that failed to parse as JSONRPC.
=> [QoS][EVM] Include Endpoint Address in log indicating unmarshal failure

qos/cometbft/qos.go
Add service_id label to CometBFT QoS log entries.
Missing service_id from CometBFT log entries.
=> Set service_id on CometBFT log entries

log/preview.go, metrics/qos/qos.go, qos/cometbft/response.go, qos/evm/response.go, qos/solana/context.go, qos/solana/response.go, qos/solana/response_generic.go
Include endpoint payload in log entries if response validation fails
- New log package to reuse logging functionality: string preview.
- EVM QoS: Include endpoint payload in log entries if response validation fails
- Solana QoS: Include endpoint payload in log entries if response validation fails
- CometBFT QoS: Include endpoint payload in log entries if response validation fails
No details on the payload that failed JSONRPC response validation.
=> [QoS] Include endpoint payload preview if response validation fails

config/service_qos_config.go
Add support for `xrplevm` chain to the service QoS configuration.
- Introduced `xrplevm` chain configuration in `service_qos_config.go`
- Added support for `xrplevm_1440000-1` network identifier
- Enabled multiple RPC types for `xrplevm`, including JSON-RPC, REST, COMET_BFT, and WebSocket
- Removed obsolete TODOs referencing upcoming `xrplevm` MainNet and Devnet support
- Minor formatting adjustment to variable alignment for consistency
=> [QoS] add xrplevm to service_qos_config.go

e2e/service_evm_test.go, e2e/service_solana_test.go, qos/jsonrpc/response.go, qos/jsonrpc/response_test.go
Refactor JSONRPC Response.Result field to use *json.RawMessage for better null handling and field presence distinction
- Changed Result field from any to *json.RawMessage to distinguish between absent field vs explicit null values
- Updated Validate() method to properly check field presence using pointer nil vs non-nil distinction
- Modified GetResultAsBytes() to return raw bytes directly without re-marshaling< Change 1 >
- Added UnmarshalResult() helper method for type-safe result unmarshaling
- Added comprehensive test coverage for JSON marshaling/unmarshaling scenarios
- Updated all existing tests to use json.RawMessage format for result values
There are valid JSONRPC responses with `"result": null`, which fail our JSONRPC validation:
Example:
```bash
curl https://rpc.xrplevm.org -d …
```
=> [QoS][JSONRPC] Fix: JSONRPC explicit null vs absent result field

config/service_qos_config.go, docusaurus/docs/learn/qos/1_supported_services.md, e2e/config/services_shannon.yaml
Add part 2 of 3 of new Cosmos SDK chains to PATH service QoS configuration
| Group 2 Service IDs |
|---------------------|
| arkeo               |
| celestia            |
| cosmoshub           |
| fetch               |
| kyve                |
| nillion             |
| persistence         |
| router              |
| side-protocol       |
- Updated e2e test configuration with new chain test cases
- Added chain registry references for all new chains
=> [Merge after #378][QoS] Add part 2 of 3 of new chains July 2025

config/service_qos_config.go, e2e/config/services_shannon.yaml
Add part 3 of 3 of new Cosmos SDK chains to PATH service QoS configuration
| Group 3 Service IDs |
|---------------------|
| atomone             |
| cheqd               |
| dungeon-chain       |
| jackal              |
| namada              |
| provenance          |
| seda                |
| stargaze            |
_(`osmosis` was already present in config file)_
- Updated e2e test configuration with new chain test cases
- Added chain registry references for all new chains
=> [Merge after #379][QoS] Add part 3 of 3 of new chains July 2025

protocol/shannon/context.go, protocol/shannon/log.go, qos/cosmos/request_validator_rest.go
Protocol only sets RPCType HTTP header on valid values
- Protocol only sets RPCType HTTP header on valid values
- Add a preview of request payload to logs to help analyze and fix endpoint errors.
=> [Protocol][Shannon] Protocol only sets RPCType HTTP header on valid values

observation/qos/solana.pb.go, observation/qos/solana_interpreter.go, proto/path/qos/solana.proto, qos/solana/response_generic.go, qos/solana/response_getepochinfo.go, qos/solana/response_gethealth.go
Add http_status_code field to SolanaEndpointObservation protobuf and update HTTP status retrieval logic
- Add HttpStatusCode field to SolanaEndpointObservation protobuf message with documentation
- Update GetRequestHTTPStatus() method to prioritize endpoint observation HTTP status over request error status
- Populate HttpStatusCode field in all Solana response handlers (responseGeneric, responseToGetEpochInfo, responseToGetHealth)
- Renumber protobuf field indices for response_observation oneof fields (2→3, 3→4, 4→5) to accommodate new http_status_code field
- Regenerate protobuf Go code with updated field definitions and getter methods
Solana metrics need to track endpoint 500 status codes
=> [QoS][Solana][Observability] Fix: qos solana endpoint 500 status observations

docusaurus/docs/operate/getting_started/1_quickstart.md, local/Dockerfile.dev, local/scripts/localnet.sh
Fix PATH configuration documentation links to point to correct URL path
- Updated PATH Config File documentation link in quickstart guide from `/develop/configs/config_intro` to `/develop/path/configurations_path`
- Updated PATH config documentation references in Docker and shell scripts to use the corrected URL path
- Ensured consistency across multiple files referencing PATH configuration documentation
- Updated both user-facing documentation and developer tooling references
- N/A
=> [Docs] fix: PATH configs links

metrics/protocol/shannon/metrics.go
=> [Metrics] Fix missing `endpoint_domain` when the observation has an error

config/service_qos_config.go, gateway/http_request_context.go, gateway/hydrator.go, gateway/hydrator_http.go, gateway/hydrator_websocket.go, gateway/protocol.go, gateway/qos.go, gateway/websocket_request_context.go, metrics/devtools/disqualified_endpoint_reporter.go, metrics/devtools/disqualified_endpoint_response.go, protocol/shannon/observation_websocket.go, protocol/shannon/protocol.go, protocol/shannon/sanction.go, protocol/shannon/sanctioned_endpoints_store.go, protocol/shannon/sanctions.go, protocol/shannon/websocket_context.go, qos/cosmos/request_validator_checks.go, qos/evm/service_qos_config.go, qos/evm/service_state.go, qos/noop/noop.go, qos/solana/check.go, websockets/bridge.go, websockets/connection.go, websockets/connection_test.go
Add WebSocket QoS checks with separate protocol-level endpoint sanction stores for WebSocket and HTTP RPC types.
- Add WebSocket-specific endpoint sanction store to maintain separate sanctions for WebSocket and HTTP RPC types
- Implement WebSocket connection checks in the endpoint hydrator with separate intervals for HTTP and WebSocket checks
- Extend protocol interface with WebSocket-specific methods for endpoint availability, observation application, and connection checking
- Add WebSocket support configuration to EVM service QoS configs (enabled for base and bsc chains)
- Refactor endpoint hydrator into separate HTTP and WebSocket check implementations for better maintainability
- Update metrics reporting to handle protocol-level disqualified endpoints per RPC type
- Add WebSocket …
=> [Websockets][QoS] Add websockets QoS checks with separate protocol-level endpoint sanction stores for websockets and HTTP

observation/qos/request_error.pb.go, proto/path/qos/request_error.proto, qos/evm/context.go, qos/evm/response.go, qos/request_error.go
Add new error type for JSONRPC backend service unmarshaling failures and improve error handling
- Add REQUEST_ERROR_INTERNAL_JSONRPC_BACKEND_SERVICE_UNMARSHAL_ERROR enum value to track when backend service payloads fail to parse as valid JSONRPC responses
- Implement detection logic in requestContext.GetObservations() to set this error when no valid JSONRPC responses are received from endpoints
- Add GetRequestErrorForJSONRPCBackendServiceUnmarshalError() helper function to create the new error type
- Enhanced logging in unmarshalResponse() with request context and clearer error messages for debugging
- Add helper function getSingleJSONRPCRequestPayload() for single JSONRPC request handling
- Update protobuf generated code to include the new error enum value
Distinguish backend service …
=> [QoS][EVM] Add new error type for JSONRPC backend service unmarshaling failures

qos/cosmos/response_jsonrpc.go, qos/evm/errors.go, qos/evm/response_generic.go, qos/jsonrpc/errors.go, qos/solana/response_generic.go
Standardize JSON-RPC error codes across the codebase by introducing dedicated constants and distinguishing between internal PATH errors and backend server errors
- Add new ResponseCodeBackendServerErr (-31002) constant to distinguish backend server errors from internal PATH errors
- Update ResponseCodeDefaultInternalErr from -32000 to -31001 to use non-reserved JSON-RPC error codes
- Replace hardcoded -32000 error codes throughout codebase with appropriate named constants
- Update comments to reference new constant names and provide clearer error code documentation
- Add TODO comment in evm/errors.go considering further error code granularity
Need to distinguish PATH generated JSONRPC error codes from endpoint/backend server JSONRPC error responses. …
=> [QoS][JSONRPC] Generic error responses use JSONRPC error codes not in the reserved ranges

qos/solana/request_validator.go
QoS Solana: Pass correct error to error context on request validation failure.
=> [QoS][Solana] Fix: QoS Solana pass correct error to error contexts
