- Dockerfile
- README.md
- cmd/main.go
- config/config.go
- config/config_test.go
- config/morse/gateway_config.go
- config/morse/gateway_config_test.go
- config/morse/signed_aat.go
- config/shannon/gateway_config.go
- config/shannon/gateway_config_test.go
- config/user_data.go
- e2e/shannon_relay_test.go
- gateway/gateway.go
- gateway/qos.go
- gateway/request.go
- go.mod
- qos/evm/evm.go
- relayer/morse/app.go
- relayer/morse/endpoint.go
- relayer/morse/protocol.go
- relayer/relayer.go
- relayer/shannon/app.go
- relayer/shannon/endpoint.go
- relayer/shannon/fullnode.go
- relayer/shannon/protocol.go
- request/parser.go
- request/qos_names.go
- request/qos_provider.go
- router/router.go
- router/router_test.go
Updates package name from `pokt-foundation/portal-middleware` to `buildwithgrove/path`.
> chore: update package name

- .github/workflows/run-e2e-tests.yml
- e2e/.example.test.yaml
- e2e/scripts/update_config_from_secrets.sh
This PR adds the GH workflow file plus other pieces necessary to run the E2E tests:
- A script to update the E2E config file from Repo's secret(s).
- A new `yml` file under GitHub workflows directory.
> Add GitHub action go E2E test v0

- gateway/gateway.go
- relayer/morse/protocol.go
- relayer/shannon/grpc.go
- relayer/shannon/protocol.go
- router/router_test.go
Required for https://github.com/buildwithgrove/path/pull/17 to pass CI workflows.
> chore: fix linter warnings

- .github/workflows/main-build.yml
- .github/workflows/release-artifacts.yml
- .github/workflows/run-tests.yml
Need to enable manual trigger of workflows: https://stackoverflow.com/questions/58933155/manual-workflow-triggers-in-github-actions
> Add `workflow_dispatch` trigger to be able to run workflows manually

- cmd/hydrator.go
- cmd/main.go
- config/config_test.go
- config/morse/gateway_config.go
- config/morse/gateway_config_test.go
- gateway/hydrator.go
- qos/evm/context.go
- qos/evm/store.go
- relayer/endpoint.go
- relayer/morse/app.go
- relayer/morse/context.go
- relayer/morse/endpoint.go
- relayer/morse/protocol.go
- relayer/protocol.go
- relayer/relayer.go
- relayer/shannon/app.go
- relayer/shannon/context.go
- relayer/shannon/endpoint.go
- relayer/shannon/protocol.go
- Refactor the protocol integration code for both `Morse` and `Shannon` to resolve endpoint selection tech debt.
- This prepare the `Shannon` integration package for adding the `Lazy mode` feature.
> [Protocol] Refactor protocol endpoints selector

- .github/workflows/main-build.yml
- cmd/qos.go
- e2e/shannon.example.yaml
- qos/evm/observe.go
- qos/evm/store.go
Fix the github workflow file to allow manually triggering the image push job.
Part of work on #54:
This PR is required to manually trigger the image push job.
The image push job  ensures the latest container image is uploaded to ghci.io/buildwithgrove/path repository. 
The resulting PATH image is used by the [helm charts for deploying PATH](https://github.com/buildwithgrove/helm-charts)
> [Infra] Fix workflow condition for manual trigger

- README.md
Add reference to inspiration from Nodie's Gateway Server
> Update README.md w/ reference to Gateway Server

- .github/workflows/upload-pages-artifact.yml
- Makefile
Added update_docs target to makefile and workflow.
> [PATCH][READY] Added update_docs target

- .github/workflows/upload-pages-artifact.yml
- README.md
- docusaurus/docs/README.md
Update docs missed the checkout. Moved to deploy docs to avoid additional step dependency.
> Fix docs workflow

- .github/workflows/run-tests.yml
- Makefile
- config/config.schema.yaml
- e2e/morse.example.yaml
- protocol/morse/protocol.go
- test_.sh
Also adds some small tweaks to example config YAML and fixes the config YAML schema to allow correct validation.
> fix: update to run E2E tests for morse/shannon in parallel 

- LICENSE
- README.md
Adding MIT license to the repo.
> [Docs] Add MIT license

- e2e/shannon.example.yaml
Update Shannon Example Config for E2E tests with Shannon Beta Testnet URLs.
> Update Shannon E2E config with Shannon Beta Testnet URLs

- gateway/gateway.go
Add logging for all cases of processing HTTP requests in the gateway.
> [Logging] Add logging in the HTTP request processing path

- Makefile
- README.md
- docusaurus/docs/README.md
- envoy/README.md
- local/kubernetes/envoy-ratelimit.yaml
- local/kubernetes/path-values.yaml
- makefiles/localnet.mk
Some edits/improvements
1. Some makefile targets no longer exist
2. Docker-compose no longer exists
3. Running `path_down` + `path_up` should be idempotent and "easy"
Where am I right now:
- DId not dive deep yet
- I'm using the configs here:
https://www.notion.so/buildwithgrove/Shannon-Alpha-Beta-Environment-rc-helpers-152a36edfff680019314d468fad88864?pvs=4
- Stopped at this issue:
https://github.com/user-attachments/assets/467db782-b00b-4c96-9c74-6228b997f396
> [WIP] Review #60

- Makefile
- README.md
- docusaurus/docs/README.md
- envoy/README.md
Update path_run target with config notes
Update README.md TOC
> Update README.md with new make targets

- qos/evm/context.go
- qos/evm/endpoint.go
Increase the endpoint response timeout on EVM-based services.
> Update EVM service timeout to 10s

- docusaurus/docs/develop/envoy/walkthrough.md
- docusaurus/docs/develop/path/cheatsheet.md
- docusaurus/docs/develop/path/path_config.md
Minor docs fixes spotted from read throughs of the docs.
> chore: minor docs fixes

- docs/.github/ISSUE_TEMPLATE/improve_docs.md
Add a new issue template for improving documentation.
* Create `docs/.github/ISSUE_TEMPLATE/improve_docs.md` file
* Add a title "Improve Documentation"
* Add a description section for a brief description of the issue
* Add checklists for selecting "Morse" or "Shannon"
* Add checklists for selecting "Developer" or "Operator"
* Add checklists for selecting "New" or "Experienced"
* Add a section for unclear documentation pages with a placeholder link
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/buildwithgrove/path/pull/136?shareId=10b03870-d95b-42f6-b610-459e821c2c67).
> Add issue template for improving documentation

- Makefile
> fix: makefile path_run config flag

- docs/.github/ISSUE_TEMPLATE/feedback.md
Add a new GitHub issue template for feedback.
* Create `docs/.github/ISSUE_TEMPLATE/feedback.md` file
* Prefill the title with "Feedback from user"
* Add sections for "What I tried", "Next steps", and "n00b questions"
* Include checkboxes for feedback type and fields for overall feedback and suggestions
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/buildwithgrove/path/pull/153?shareId=2c8ea843-405f-40da-b093-91ad737d66cb).
> Add feedback issue template

- .github/pull_request_template.md
- Dockerfile
- Makefile
- Tiltfile
- cmd/main.go
- envoy/auth_server/Dockerfile
- local/kubernetes/envoy-ext-authz.yaml
- local/kubernetes/path-values.yaml
- makefiles/localnet.mk
- makefiles/test_requests.mk
Let me analyze the PR changes and create a description.
Enhance local development setup with improved PATH config management and QoS testing infrastructure
- Migrate PATH config management from `ConfigMap` to `Secret` with hot-reload support in Tilt
- Add comprehensive QoS test checklist with test commands for different environments
- Implement checks for PATH service availability before running test requests 
- Refactor Dockerfile configurations with improved layer caching and config directory setup
- Update Tilt configuration for better hot-reload support
- Clean up deprecated `config_path_secrets` make target and related commands
1. Copy these to files from 1password to my local workspace (outside of the `path` repo) into `/shannon_config.yaml` and `/shannon_config.yaml` respectivel
2. …
> [Tilt] A few LocalNet Quality of Life Improvements as discord conversation followsups

- gateway/hydrator.go
> [Bug] Fix broken hydrator observations

- .github/workflows/main-build.yml
Extends https://github.com/buildwithgrove/path/pull/231
> [CI] Build image on main - remove redundant check

- .github/workflows/run-e2e-tests.yml
- .github/workflows/run-lint-and-test.yml
- Dockerfile
- Tiltfile
- docusaurus/yarn.lock
- go.mod
- go.sum
- makefiles/debug.mk
- makefiles/localnet.mk
Necessary to align with the changes here: https://github.com/pokt-network/poktroll/pull/1307
> Bump go version from `v1.23.0` to `v.1.24.3`

- e2e/config/.grove.archival.e2e_load_test.config.yaml
- e2e/config/.grove.e2e_load_test.config.yaml
- e2e/config/e2e_load_test.config.tmpl.yaml
- e2e/config/services_shannon.yaml
- e2e/config_test.go
- Minor fixes to load test configs
- Minor improvements to load test scripts
- Increase default test from 50 RPS / 30 Req to 100 RPS / 300 Req
- Accompanying doc: https://www.notion.so/buildwithgrove/PATH-Shannon-to-214a36edfff6809c9c5bf7cb7d8d8d23?source=copy_link
> [Tooling] Increasing the load on PATH performance

- config/service_qos_config.go
- e2e/config/services_shannon.yaml
- e2e/config_test.go
- e2e/main_test.go
- e2e/service_evm_test.go
- e2e/service_solana_test.go
- e2e/vegeta_test.go
- gateway/request_context.go
- protocol/shannon/context.go
- protocol/shannon/endpoint.go
- qos/cometbft/state.go
- qos/cometbft/store.go
- qos/evm/endpoint.go
- qos/evm/endpoint_selection.go
- qos/evm/request_validator.go
- qos/evm/service_state.go
- qos/evm/state_archival.go
- qos/solana/endpoint.go
- qos/solana/request_validator.go
- qos/solana/response_getepochinfo.go
- qos/solana/response_gethealth.go
- qos/solana/state.go
- qos/solana/store.go
- websockets/bridge.go
- websockets/connection.go
Improve Near chain support, enhance error logging with emojis, and refactor E2E testing infrastructure
- Remove `near` from EVM services and add proper Near-specific QoS configuration with TODO for full implementation
- Upgrade error logging from `Info` to `Error` level across QoS modules with descriptive emoji indicators
- Refactor E2E test execution flow by removing manual pass/fail tracking and improving test output formatting
- Optimize archival balance consensus checking with parallel processing and proper timeout handling
- Add comprehensive TODO list for unsupported services in `services_shannon.yaml`
- Enhance E2E test progress reporting with better visual separators and service summaries
- Improve error messages with service-specific context and endpoint identification
- Add …
> [Testing] Logging improvements, better archival checks, and improved load test scripts

- .github/workflows/run-lint-and-test.yml
- .golangci.yml
- cmd/data.go
- data/reporter_http.go
- gateway/errors.go
- gateway/hydrator.go
- gateway/request_context.go
- message/qos/qos.go
- protocol/morse/errors.go
- protocol/morse/fullnode.go
- protocol/shannon/context.go
- protocol/shannon/errors.go
- protocol/shannon/gateway_mode.go
- protocol/shannon/mode_centralized.go
- protocol/shannon/mode_delegated.go
- protocol/shannon/protocol.go
- protocol/shannon/sanctions.go
- qos/cometbft/cometbft.go
- qos/cometbft/context.go
- qos/cometbft/service_qos_config.go
- qos/evm/context.go
- qos/evm/qos.go
- qos/request_error.go
- qos/solana/context.go
- qos/solana/endpoint.go
- qos/solana/response_generic.go
- qos/solana/solana.go
- qos/solana/state.go
- request/errors.go
Fixed by Claude code after running `make go_lint`
> [Linter] Fix linting issues

- observation/qos/cosmos_response.pb.go
- proto/path/qos/cosmos_response.proto
- qos/cosmos/check_cometbft_health.go
- qos/cosmos/check_cometbft_status.go
- qos/cosmos/check_cosmos_status.go
- qos/cosmos/endpoint.go
- qos/cosmos/endpoint_selection.go
- qos/cosmos/request_validator_checks.go
- qos/cosmos/response_cometbft_status.go
- qos/cosmos/response_cosmos_status.go
- qos/cosmos/response_jsonrpc.go
- qos/cosmos/response_rest.go
- qos/cosmos/service_state_endpoint_selection.go
- qos/cosmos/service_state_endpoint_validation.go
- qos/evm/check_archival.go
- qos/evm/check_blocknumber.go
- qos/evm/check_chainid.go
> Basic review

- local/scripts/curl_abci_info_monitor.sh
- local/scripts/curl_load_test_session_rollover.sh
Usage:
```bash
./local/scripts/curl_abci_info_monitor.sh # --help
./local/scripts/curl_load_test_session_rollover.sh # --help
```
> [Scripts] Add scripts to curl endpoints

- gateway/gateway.go
- gateway/protocol.go
- gateway/request_context.go
- gateway/websocket.go
- protocol/shannon/context.go
- protocol/shannon/observation.go
- protocol/shannon/websocket_connection.go
- protocol/shannon/websocket_handlers.go
- protocol/shannon/websocket_test.go
- router/router_test.go
- websockets/bridge.go
- websockets/bridge_test.go
- websockets/connection.go
- websockets/connection_test.go
> [Review] Review of #386

- gateway/protocol.go
- gateway/request_context.go
- protocol/shannon/config.go
- protocol/shannon/context.go
- protocol/shannon/endpoint.go
- protocol/shannon/protocol.go
- websockets/bridge.go
- websockets/bridge_test.go
QoL improvements post-merge while building context of #396
> [Review] Post-merge review of #396

- gateway/gateway.go
- gateway/http_request_context_handle_request.go
- observation/protocol/shannon.pb.go
- proto/path/protocol/shannon.proto
- protocol/shannon/context.go
- qos/evm/request_validator.go
TODOs for batch JSONRPC requests feature.
> Add initial set of TODOs for batch request processing

- protocol/shannon/sanctions.go
Relax sanctioning rules on uncategorized errors
> [Protocol][Shannon] Relax sanctioning rules on uncategorized errors

- metrics/protocol/shannon/metrics.go
- protocol/shannon/sanctioned_endpoints_store.go
Fix protocol observations request errors
> [Observability][Shannon] Fix protocol observations request errors

- config/service_qos_config.go
- e2e/config/e2e_load_test.config.default.yaml
- router/router.go
- Adding unichain & hyperliquid
- TODOs for archival
- Updated some comments
> [New Chains] Unichain & Hyperliquid

- protocol/shannon/config.go
- protocol/shannon/context.go
- protocol/shannon/endpoint.go
- protocol/shannon/protocol.go
Support Load Testing against a RelayMiner via config
> [Load Testing][Tooling] Support Load Testing against a RelayMiner via config
